export const list = {
  provider: "KADO",
  chainId: "fiat",
  name: "KADO",
  timestamp: "2024-09-25T15:31:06.827Z",
  version: {
    major: 1,
    minor: 0,
    patch: 0,
  },
  keywords: [],
  count: 27,
  tokens: [
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.USD",
      logoURI: "",
      ticker: "USD",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.CAD",
      logoURI: "",
      ticker: "CAD",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.GBP",
      logoURI: "",
      ticker: "GBP",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.EUR",
      logoURI: "",
      ticker: "EUR",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.MXN",
      logoURI: "",
      ticker: "MXN",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.COP",
      logoURI: "",
      ticker: "COP",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.INR",
      logoURI: "",
      ticker: "INR",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.CHF",
      logoURI: "",
      ticker: "CHF",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.AUD",
      logoURI: "",
      ticker: "AUD",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.ARS",
      logoURI: "",
      ticker: "ARS",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.BRL",
      logoURI: "",
      ticker: "BRL",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.CLP",
      logoURI: "",
      ticker: "CLP",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.JPY",
      logoURI: "",
      ticker: "JPY",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.KRW",
      logoURI: "",
      ticker: "KRW",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.PEN",
      logoURI: "",
      ticker: "PEN",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.PHP",
      logoURI: "",
      ticker: "PHP",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.SGD",
      logoURI: "",
      ticker: "SGD",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.TRY",
      logoURI: "",
      ticker: "TRY",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.UYU",
      logoURI: "",
      ticker: "UYU",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.TWD",
      logoURI: "",
      ticker: "TWD",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.VND",
      logoURI: "",
      ticker: "VND",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.CRC",
      logoURI: "",
      ticker: "CRC",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.SEK",
      logoURI: "",
      ticker: "SEK",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.PLN",
      logoURI: "",
      ticker: "PLN",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.DKK",
      logoURI: "",
      ticker: "DKK",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.NOK",
      logoURI: "",
      ticker: "NOK",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.NZD",
      logoURI: "",
      ticker: "NZD",
    },
  ],
} as const;
