export const list = {
  name: 'native-l1',
  timestamp: '2023-10-17T00:00:00.000Z',
  version: { major: 1, minor: 0, patch: 0 },
  keywords: ['Native'],
  tokens: [
    { address: '1C9', chain: 'BNB', identifier: 'BNB.ETH-1C9', decimals: 8 },
    { address: '1DE', chain: 'BNB', identifier: 'BNB.BTCB-1DE', decimals: 8 },
    { address: '645', chain: 'BNB', identifier: 'BNB.AVA-645', decimals: 8 },
    { address: '8C2', chain: 'BNB', identifier: 'BNB.TWT-8C2', decimals: 8 },
    { address: 'BD1', chain: 'BNB', identifier: 'BNB.BUSD-BD1', decimals: 8 },
    { chain: 'AVAX', identifier: 'AVAX.AVAX', decimals: 18 },
    { chain: 'BCH', identifier: 'BCH.BCH', decimals: 8 },
    { chain: 'BNB', identifier: 'BNB.BNB', decimals: 8 },
    { chain: 'BSC', identifier: 'BSC.BNB', decimals: 18 },
    { chain: 'BTC', identifier: 'BTC.BTC', decimals: 8 },
    { chain: 'DOGE', identifier: 'DOGE.DOGE', decimals: 8 },
    { chain: 'ETH', identifier: 'ETH.ETH', decimals: 18 },
    { chain: 'GAIA', identifier: 'GAIA.ATOM', decimals: 6 },
    { chain: 'LTC', identifier: 'LTC.LTC', decimals: 8 },
    { chain: 'THOR', identifier: 'THOR.RUNE', decimals: 8 },
  ],
  count: 15,
  logo: 'https://static.thorswap.finance/logo.png',
} as const;
