docs:
  - internal/playground/**/*
  - docs/**/*

api: packages/swapkit/api/**/*
tokens: packages/swapkit/tokens/**/*
core:
  - packages/swapkit/core/**/*
  - packages/swapkit/helpers/**/*
  - packages/swapkit/types/**/*

cosmos: packages/toolboxes/cosmos/**/*
evm: packages/toolboxes/evm/**/*
solana: packages/toolboxes/solana/**/*
substrate: packages/toolboxes/substrate/**/*
utxo: packages/toolboxes/utxo/**/*
radix:
  - packages/toolboxes/radix/**/*
  - packages/wallets/radix/src/**/*

keystore: packages/wallets/keystore/**/*
hardware-wallet:
  - packages/wallets/ledger/src/**/*
  - packages/wallets/trezor/src/**/*
  - packages/wallets/keepkey/src/**/*

mobile-wallet:
  - packages/wallets/wc/**/*
  - packages/wallets/exodus/**/*
  - packages/wallets/coinbase/**/*

browser-extensions:
  - packages/wallets/evm-extensions/**/*
  - packages/wallets/keplr/**/*
  - packages/wallets/okx/**/*
  - packages/wallets/phantom/**/*
  - packages/wallets/xdefi/**/*
