import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavigationBar } from "~/components/containers/NavigationBar";
import { AppProviders } from "~/components/providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AppProviders>
          <div className="max-w-[800px] mx-auto">
            <NavigationBar />
            <div className="items-center justify-center flex">{children}</div>
          </div>
        </AppProviders>
      </body>
    </html>
  );
}
